spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    # 数字要带上双引号
    password: root
    url: jdbc:mysql://localhost:3306/socket_db?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource


# 线程池配置
threadPool:
  corePoolSize: 2
  maximumPoolSize: 4
  workQueueSize: 2