spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    # 数字要带上双引号
    password: "1234"
    url: jdbc:mysql://localhost:3306/socket_db?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
