# 线程池配置
threadPool:
  corePoolSize: 6
  maximumPoolSize: 10
  workQueueSize: 10

# 服务端的ip地址和端口
socket:
  ip: 192.168.137.105
  port: 8080

client:
  port: 8083
  udp:
    port: 8084


logging:
  config: classpath:logback-spring.xml
  level:
    root: info
