# 线程池配置
threadPool:
  corePoolSize: 2
  maximumPoolSize: 4
  workQueueSize: 2

# 服务端的ip地址和端口
socket:
  ip: 127.0.0.1
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
