# 线程池配置
threadPool:
  corePoolSize: 6
  maximumPoolSize: 10
  workQueueSize: 10

# 服务端的ip地址和端口
socket:
  ip: 127.0.0.1
  port: 8080

client:
  port: 8082
  udp:
    port: 8082


logging:
  config: classpath:logback-spring.xml
  level:
    root: info
